package Entidad;
// Generated 20/10/2022 16:46:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private Integer idAutor;
     private String nombreAutor;
     private int estado;
     private Set<Libro> libros = new HashSet<Libro>(0);

    public Autor() {
    }

	
    public Autor(String nombreAutor, int estado) {
        this.nombreAutor = nombreAutor;
        this.estado = estado;
    }
    public Autor(String nombreAutor, int estado, Set<Libro> libros) {
       this.nombreAutor = nombreAutor;
       this.estado = estado;
       this.libros = libros;
    }
   
    public Integer getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(Integer idAutor) {
        this.idAutor = idAutor;
    }
    public String getNombreAutor() {
        return this.nombreAutor;
    }
    
    public void setNombreAutor(String nombreAutor) {
        this.nombreAutor = nombreAutor;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set<Libro> getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set<Libro> libros) {
        this.libros = libros;
    }




}


