package Entidad;
// Generated 20/10/2022 16:46:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String categoria;
     private int estado;
     private Set<Libro> libros = new HashSet<Libro>(0);

    public Categoria() {
    }

	
    public Categoria(String categoria, int estado) {
        this.categoria = categoria;
        this.estado = estado;
    }
    public Categoria(String categoria, int estado, Set<Libro> libros) {
       this.categoria = categoria;
       this.estado = estado;
       this.libros = libros;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set<Libro> getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set<Libro> libros) {
        this.libros = libros;
    }




}


