package Entidad;
// Generated 20/10/2022 16:46:01 by Hibernate Tools 4.3.1



/**
 * Devoluciones generated by hbm2java
 */
public class Devoluciones  implements java.io.Serializable {


     private Integer idDevolucion;
     private Cliente cliente;
     private Libro libro;
     private String comentario;

    public Devoluciones() {
    }

    public Devoluciones(Cliente cliente, Libro libro, String comentario) {
       this.cliente = cliente;
       this.libro = libro;
       this.comentario = comentario;
    }
   
    public Integer getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(Integer idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


