package Entidad;
// Generated 20/10/2022 16:46:01 by Hibernate Tools 4.3.1



/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer idPrestamo;
     private Cliente cliente;
     private Libro libro;
     private String fechaPrestado;
     private String fechaDevolucion;
     private int estado;

    public Prestamo() {
    }

    public Prestamo(Cliente cliente, Libro libro, String fechaPrestado, String fechaDevolucion, int estado) {
       this.cliente = cliente;
       this.libro = libro;
       this.fechaPrestado = fechaPrestado;
       this.fechaDevolucion = fechaDevolucion;
       this.estado = estado;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public String getFechaPrestado() {
        return this.fechaPrestado;
    }
    
    public void setFechaPrestado(String fechaPrestado) {
        this.fechaPrestado = fechaPrestado;
    }
    public String getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(String fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


